## RapidMeta Neurology | Anti-Amyloid mAbs NMA in Early Alzheimer Disease v1.1 — netmeta validation
## Auto-generated by nma_r_validate_template.py
suppressPackageStartupMessages({ library(netmeta); library(meta) })

logHR_SE <- function(hr, lci, uci) {
  list(TE = log(hr), seTE = (log(uci) - log(lci)) / 3.92)
}

# From config.comparisons + config.realData (one row per edge×trial)
trials <- data.frame(
  studlab = c("Clarity AD","TRAILBLAZER-ALZ 2","EMERGE"),
  treat1  = c("Lecanemab","Donanemab","Aducanumab"),
  treat2  = c("Placebo","Placebo","Placebo"),
  TE      = c(-0.3147107448,-0.3424903089,-0.2484613593),
  seTE    = c(0.0905699629,0.0858347542,0.1167941565),
  stringsAsFactors = FALSE
)
cat("=== RapidMeta Neurology | Anti-Amyloid mAbs NMA in Early Alzheimer Disease v1.1 ===\n")
print(trials)
cat("\n")

nma <- netmeta(TE=TE, seTE=seTE, treat1=treat1, treat2=treat2, studlab=studlab,
               data=trials, sm="HR", reference.group="Placebo",
               common=TRUE, random=TRUE)

cat("\n=== Consistency model ===\n")
print(summary(nma))
cat("\n=== League table (RE, HR/RR with 95% CI) ===\n")
print(netleague(nma, digits=3, common=FALSE, random=TRUE)$random)
cat("\n=== Design-by-treatment inconsistency ===\n")
print(decomp.design(nma))
cat("\n=== Node-splitting ===\n")
print(netsplit(nma, common=FALSE, random=TRUE))
cat("\n=== P-scores (lower = better for HR/RR on protective scale) ===\n")
rk <- netrank(nma, small.values="desirable", common=FALSE, random=TRUE)
print(rk)

# MC rank-probability matrix
set.seed(42)
n_draws <- 1e5
trts <- nma$trts
n_trt <- length(trts)
se_contrast <- nma$seTE.random[, "Placebo"]
mu <- nma$TE.random[, "Placebo"]
draws <- matrix(0, nrow=n_draws, ncol=n_trt)
colnames(draws) <- trts
for (i in seq_along(trts)) {
  if (trts[i] == "Placebo") next
  draws[, i] <- rnorm(n_draws, mu[trts[i]], se_contrast[trts[i]])
}
ranks <- t(apply(draws, 1, rank, ties.method="random"))
colnames(ranks) <- trts
rank_prob <- matrix(0, nrow=n_trt, ncol=n_trt,
                    dimnames=list(trts, paste0("rank_", seq_len(n_trt))))
for (i in seq_len(n_trt)) for (r in seq_len(n_trt)) rank_prob[i, r] <- mean(ranks[, i] == r)
sucra <- sapply(seq_len(n_trt), function(i) mean(cumsum(rank_prob[i, -n_trt])))
names(sucra) <- trts
cat("\n=== Rank-probability matrix (N=100k draws) ===\n")
print(round(rank_prob, 3))
cat("\n=== SUCRA ===\n")
print(round(sort(sucra, decreasing=TRUE), 3))

# JSON output
results <- list(
  title = "RapidMeta Neurology | Anti-Amyloid mAbs NMA in Early Alzheimer Disease v1.1",
  treatments = trts,
  te_random_vs_ref   = setNames(nma$TE.random[, "Placebo"], trts),
  se_random_vs_ref   = setNames(nma$seTE.random[, "Placebo"], trts),
  hr_random_vs_chemoimm = setNames(exp(nma$TE.random[, "Placebo"]), trts),
  hr_ci_lower   = setNames(exp(nma$lower.random[, "Placebo"]), trts),
  hr_ci_upper   = setNames(exp(nma$upper.random[, "Placebo"]), trts),
  tau2 = nma$tau^2,
  I2 = nma$I2,
  Q_total = nma$Q,
  Q_heterogeneity = nma$Q.heterogeneity,
  Q_inconsistency = nma$Q.inconsistency,
  p_inconsistency = nma$pval.Q.inconsistency,
  sucra = sucra,
  pscore_random = rk$ranking.random,
  rank_prob = rank_prob
)
saveRDS(results, "antiamyloid_ad_nma_netmeta_results.rds")
tryCatch({
  suppressPackageStartupMessages(library(jsonlite))
  writeLines(toJSON(lapply(results, function(x) if (is.matrix(x)) { m <- as.matrix(x); dimnames(m) <- NULL; m } else x), digits=6, auto_unbox=TRUE),
             "antiamyloid_ad_nma_netmeta_results.json")
  cat("\n[wrote antiamyloid_ad_nma_netmeta_results.rds + .json]\n")
}, error = function(e) cat("\n[JSON skipped:", conditionMessage(e), "]\n"))
cat("\n=== Key results for peer-review bundle ===\n")
cat("TAU2:", round(nma$tau^2, 5), "\n")
cat("I2:", round(nma$I2 * 100, 2), "%\n")
cat("Q inc:", round(nma$Q.inconsistency, 3), "df", nma$df.Q.inconsistency, "p", round(nma$pval.Q.inconsistency, 4), "\n")
for (tr in trts) {
  if (tr == "Placebo") next
  cat(sprintf("  %-24s %s %.3f (%.3f, %.3f)\n",
              tr, "HR",
              exp(nma$TE.random[tr, "Placebo"]),
              exp(nma$lower.random[tr, "Placebo"]),
              exp(nma$upper.random[tr, "Placebo"])))
}
