## RapidMeta Haematology | BTKi Class NMA in CLL v1.2 — netmeta validation
## Auto-generated by nma_r_validate_template.py
suppressPackageStartupMessages({ library(netmeta); library(meta) })

logHR_SE <- function(hr, lci, uci) {
  list(TE = log(hr), seTE = (log(uci) - log(lci)) / 3.92)
}

# From config.comparisons + config.realData (one row per edge×trial)
trials <- data.frame(
  studlab = c("ELEVATE-RR","ELEVATE-TN","RESONATE-2","ALPINE","SEQUOIA"),
  treat1  = c("Acalabrutinib","Acalabrutinib","Ibrutinib","Zanubrutinib","Zanubrutinib"),
  treat2  = c("Ibrutinib","Chemoimmunotherapy","Chemoimmunotherapy","Ibrutinib","Chemoimmunotherapy"),
  TE      = c(0.0000000000,-1.5606477483,-1.9241486573,-0.4307829161,-0.8675005677),
  seTE    = c(0.1086307171,0.2108873911,0.2039611184,0.1435017852,0.2068699531),
  stringsAsFactors = FALSE
)
cat("=== RapidMeta Haematology | BTKi Class NMA in CLL v1.2 ===\n")
print(trials)
cat("\n")

nma <- netmeta(TE=TE, seTE=seTE, treat1=treat1, treat2=treat2, studlab=studlab,
               data=trials, sm="HR", reference.group="Chemoimmunotherapy",
               common=TRUE, random=TRUE)

cat("\n=== Consistency model ===\n")
print(summary(nma))
cat("\n=== League table (RE, HR/RR with 95% CI) ===\n")
print(netleague(nma, digits=3, common=FALSE, random=TRUE)$random)
cat("\n=== Design-by-treatment inconsistency ===\n")
print(decomp.design(nma))
cat("\n=== Node-splitting ===\n")
print(netsplit(nma, common=FALSE, random=TRUE))
cat("\n=== P-scores (lower = better for HR/RR on protective scale) ===\n")
rk <- netrank(nma, small.values="desirable", common=FALSE, random=TRUE)
print(rk)

# MC rank-probability matrix
set.seed(42)
n_draws <- 1e5
trts <- nma$trts
n_trt <- length(trts)
se_contrast <- nma$seTE.random[, "Chemoimmunotherapy"]
mu <- nma$TE.random[, "Chemoimmunotherapy"]
draws <- matrix(0, nrow=n_draws, ncol=n_trt)
colnames(draws) <- trts
for (i in seq_along(trts)) {
  if (trts[i] == "Chemoimmunotherapy") next
  draws[, i] <- rnorm(n_draws, mu[trts[i]], se_contrast[trts[i]])
}
ranks <- t(apply(draws, 1, rank, ties.method="random"))
colnames(ranks) <- trts
rank_prob <- matrix(0, nrow=n_trt, ncol=n_trt,
                    dimnames=list(trts, paste0("rank_", seq_len(n_trt))))
for (i in seq_len(n_trt)) for (r in seq_len(n_trt)) rank_prob[i, r] <- mean(ranks[, i] == r)
sucra <- sapply(seq_len(n_trt), function(i) mean(cumsum(rank_prob[i, -n_trt])))
names(sucra) <- trts
cat("\n=== Rank-probability matrix (N=100k draws) ===\n")
print(round(rank_prob, 3))
cat("\n=== SUCRA ===\n")
print(round(sort(sucra, decreasing=TRUE), 3))

# JSON output
results <- list(
  title = "RapidMeta Haematology | BTKi Class NMA in CLL v1.2",
  treatments = trts,
  te_random_vs_ref   = setNames(nma$TE.random[, "Chemoimmunotherapy"], trts),
  se_random_vs_ref   = setNames(nma$seTE.random[, "Chemoimmunotherapy"], trts),
  hr_random_vs_chemoimm = setNames(exp(nma$TE.random[, "Chemoimmunotherapy"]), trts),
  hr_ci_lower   = setNames(exp(nma$lower.random[, "Chemoimmunotherapy"]), trts),
  hr_ci_upper   = setNames(exp(nma$upper.random[, "Chemoimmunotherapy"]), trts),
  tau2 = nma$tau^2,
  I2 = nma$I2,
  Q_total = nma$Q,
  Q_heterogeneity = nma$Q.heterogeneity,
  Q_inconsistency = nma$Q.inconsistency,
  p_inconsistency = nma$pval.Q.inconsistency,
  sucra = sucra,
  pscore_random = rk$ranking.random,
  rank_prob = rank_prob
)
saveRDS(results, "btki_cll_nma_netmeta_results.rds")
tryCatch({
  suppressPackageStartupMessages(library(jsonlite))
  writeLines(toJSON(lapply(results, function(x) if (is.matrix(x)) { m <- as.matrix(x); dimnames(m) <- NULL; m } else x), digits=6, auto_unbox=TRUE),
             "btki_cll_nma_netmeta_results.json")
  cat("\n[wrote btki_cll_nma_netmeta_results.rds + .json]\n")
}, error = function(e) cat("\n[JSON skipped:", conditionMessage(e), "]\n"))
cat("\n=== Key results for peer-review bundle ===\n")
cat("TAU2:", round(nma$tau^2, 5), "\n")
cat("I2:", round(nma$I2 * 100, 2), "%\n")
cat("Q inc:", round(nma$Q.inconsistency, 3), "df", nma$df.Q.inconsistency, "p", round(nma$pval.Q.inconsistency, 4), "\n")
for (tr in trts) {
  if (tr == "Chemoimmunotherapy") next
  cat(sprintf("  %-24s %s %.3f (%.3f, %.3f)\n",
              tr, "HR",
              exp(nma$TE.random[tr, "Chemoimmunotherapy"]),
              exp(nma$lower.random[tr, "Chemoimmunotherapy"]),
              exp(nma$upper.random[tr, "Chemoimmunotherapy"])))
}
