## RapidMeta Cardiology | DOAC Class NMA vs Warfarin for Stroke Prevention in AF v1.0 — netmeta validation
## Auto-generated by nma_r_validate_template.py
suppressPackageStartupMessages({ library(netmeta); library(meta) })

logHR_SE <- function(hr, lci, uci) {
  list(TE = log(hr), seTE = (log(uci) - log(lci)) / 3.92)
}

# From config.comparisons + config.realData (one row per edge×trial)
trials <- data.frame(
  studlab = c("RE-LY","ROCKET-AF","ARISTOTLE","ENGAGE-AF-TIMI-48"),
  treat1  = c("Dabigatran","Rivaroxaban","Apixaban","Edoxaban"),
  treat2  = c("Warfarin","Warfarin","Warfarin","Warfarin"),
  TE      = c(-0.4155154440,-0.2357223335,-0.2357223335,-0.2357223335),
  seTE    = c(0.1113335035,0.0955850636,0.0929138137,0.1153023275),
  stringsAsFactors = FALSE
)
cat("=== RapidMeta Cardiology | DOAC Class NMA vs Warfarin for Stroke Prevention in AF v1.0 ===\n")
print(trials)
cat("\n")

nma <- netmeta(TE=TE, seTE=seTE, treat1=treat1, treat2=treat2, studlab=studlab,
               data=trials, sm="HR", reference.group="Warfarin",
               common=TRUE, random=TRUE,
               method.tau="REML",   # REML per protocol (NOT DL, which is the netmeta default)
               hakn=TRUE)            # HKSJ (Hartung-Knapp-Sidik-Jonkman) CI adjustment

cat("\n=== Consistency model ===\n")
print(summary(nma))
cat("\n=== League table (RE, HR/RR with 95% CI) ===\n")
print(netleague(nma, digits=3, common=FALSE, random=TRUE)$random)
cat("\n=== Design-by-treatment inconsistency ===\n")
print(decomp.design(nma))
cat("\n=== Node-splitting ===\n")
print(netsplit(nma, common=FALSE, random=TRUE))
cat("\n=== P-scores (lower = better for HR/RR on protective scale) ===\n")
rk <- netrank(nma, small.values="desirable", common=FALSE, random=TRUE)
print(rk)

# MC rank-probability matrix — correct multivariate-normal draw using
# netmeta's estimated contrast vcov (not independent rnorms; bug acknowledged
# in v1.0 of this script, fixed 2026-04-21).
set.seed(42)
suppressPackageStartupMessages(library(MASS))
n_draws <- 1e5
trts <- nma$trts
n_trt <- length(trts)
non_ref <- trts[trts != "Warfarin"]
# Mean vector: contrast vs reference for non-reference treatments
mu <- nma$TE.random[non_ref, "Warfarin"]
# Full covariance of contrasts from the fitted random-effects model
if (!is.null(nma$Cov.random)) {
  # Cov.random is keyed on treatment × treatment; extract the subset vs reference.
  # netmeta stores this as a matrix indexed by trt names in the trts order.
  cov_full <- nma$Cov.random
  # Construct contrast-vs-ref covariance for non_ref × non_ref
  # Sigma[i,j] = Cov(mu_i - mu_ref, mu_j - mu_ref)
  idx_ref <- which(trts == "Warfarin")
  idx <- which(trts %in% non_ref)
  Sigma <- matrix(0, nrow=length(non_ref), ncol=length(non_ref),
                  dimnames=list(non_ref, non_ref))
  for (a in seq_along(non_ref)) for (b in seq_along(non_ref)) {
    ia <- which(trts == non_ref[a]); ib <- which(trts == non_ref[b])
    Sigma[a, b] <- cov_full[ia, ib] - cov_full[ia, idx_ref] -
                   cov_full[idx_ref, ib] + cov_full[idx_ref, idx_ref]
  }
} else {
  # Fallback: independent — clearly marked as a limitation in this case
  Sigma <- diag(nma$seTE.random[non_ref, "Warfarin"]^2)
  warning("Cov.random unavailable; falling back to independent-contrast MC draws. Results approximate.")
}
draws_nonref <- mvrnorm(n_draws, mu, Sigma)
draws <- matrix(0, nrow=n_draws, ncol=n_trt)
colnames(draws) <- trts
for (i in seq_along(non_ref)) draws[, non_ref[i]] <- draws_nonref[, i]
# Direction: small.values="desirable" -> rank 1 = smallest (e.g., HR<1 is best)
# small.values="undesirable" -> rank 1 = largest (e.g., OR>1 is best for PASI 90)
if ("desirable" == "undesirable") draws <- -draws
ranks <- t(apply(draws, 1, rank, ties.method="random"))
colnames(ranks) <- trts
rank_prob <- matrix(0, nrow=n_trt, ncol=n_trt,
                    dimnames=list(trts, paste0("rank_", seq_len(n_trt))))
for (i in seq_len(n_trt)) for (r in seq_len(n_trt)) rank_prob[i, r] <- mean(ranks[, i] == r)
sucra <- sapply(seq_len(n_trt), function(i) mean(cumsum(rank_prob[i, -n_trt])))
names(sucra) <- trts
cat("\n=== Rank-probability matrix (N=100k draws) ===\n")
print(round(rank_prob, 3))
cat("\n=== SUCRA ===\n")
print(round(sort(sucra, decreasing=TRUE), 3))

# JSON output
# Back-transform: ratio measures use exp(), MD/SMD use identity
is_log <- "HR" %in% c("HR", "OR", "RR")
bt <- if (is_log) exp else function(x) x
results <- list(
  title = "RapidMeta Cardiology | DOAC Class NMA vs Warfarin for Stroke Prevention in AF v1.0",
  treatments = trts,
  te_random_vs_ref   = setNames(nma$TE.random[, "Warfarin"], trts),
  se_random_vs_ref   = setNames(nma$seTE.random[, "Warfarin"], trts),
  hr_random_vs_chemoimm = setNames(bt(nma$TE.random[, "Warfarin"]), trts),
  hr_ci_lower   = setNames(bt(nma$lower.random[, "Warfarin"]), trts),
  hr_ci_upper   = setNames(bt(nma$upper.random[, "Warfarin"]), trts),
  tau2 = nma$tau^2,
  I2 = nma$I2,
  Q_total = nma$Q,
  Q_heterogeneity = nma$Q.heterogeneity,
  Q_inconsistency = nma$Q.inconsistency,
  p_inconsistency = nma$pval.Q.inconsistency,
  sucra = sucra,
  pscore_random = rk$ranking.random,
  rank_prob = rank_prob
)
saveRDS(results, "doac_af_nma_netmeta_results.rds")
tryCatch({
  suppressPackageStartupMessages(library(jsonlite))
  writeLines(toJSON(lapply(results, function(x) if (is.matrix(x)) { m <- as.matrix(x); dimnames(m) <- NULL; m } else x), digits=6, auto_unbox=TRUE),
             "doac_af_nma_netmeta_results.json")
  cat("\n[wrote doac_af_nma_netmeta_results.rds + .json]\n")
}, error = function(e) cat("\n[JSON skipped:", conditionMessage(e), "]\n"))
cat("\n=== Key results for peer-review bundle ===\n")
cat("TAU2:", round(nma$tau^2, 5), "\n")
cat("I2:", round(nma$I2 * 100, 2), "%\n")
cat("Q inc:", round(nma$Q.inconsistency, 3), "df", nma$df.Q.inconsistency, "p", round(nma$pval.Q.inconsistency, 4), "\n")
for (tr in trts) {
  if (tr == "Warfarin") next
  cat(sprintf("  %-24s %s %.3f (%.3f, %.3f)\n",
              tr, "HR",
              bt(nma$TE.random[tr, "Warfarin"]),
              bt(nma$lower.random[tr, "Warfarin"]),
              bt(nma$upper.random[tr, "Warfarin"])))
}
