#!/usr/bin/env python
"""The PUBLIC BOARD — 'who else is doing this?' as a static, searchable page.

Generated from the public claims store (a file in a public claims repo). No server,
no database. A research community becoming visible to itself: a researcher in
Kampala can see a colleague claimed a malaria review three weeks ago and submitted
it last Tuesday. No evidence-synthesis tool does this.

Regenerated by the daily GitHub Action after it prunes lapsed claims.
"""
from __future__ import annotations
import json, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import claims as C

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def build(claims, now, out_path):
    rows = C.board_rows(claims, now)
    rows.sort(key=lambda r: (r['status'] != 'active', -r['claimed_at']))
    active = sum(1 for r in rows if r['status'] == 'active')
    subs = sum(1 for r in rows if r['submitted'])
    trs = ''
    for r in rows:
        badge = ('<span style="color:#3fb950">active · %d days left</span>' % r['days_remaining']) if r['status'] == 'active' \
            else ('<span style="opacity:.6">lapsed — free to claim</span>')
        sub = ' &nbsp;<span style="color:#58a6ff">&#9993; submitted</span>' if r['submitted'] else ''
        trs += (f'<tr><td>{r["review_id"]}</td><td>@{r["user"]}</td><td>{badge}{sub}</td></tr>')
    html = (
        '<title>RapidMeta — Open Reviews Board</title>'
        '<div style="font-family:system-ui,sans-serif;max-width:1000px;margin:20px auto;color:#e6edf3;background:#0d1117;padding:20px;border-radius:10px">'
        '<h2>&#128220; Open Reviews Board</h2>'
        '<p style="opacity:.8">Who is working on what, right now. <b>A claim informs — it never blocks.</b> '
        'Nobody owns a research question; if you want to work the same review, you can — you just do it '
        'knowing someone else is, and you can make contact. Two independent reviews is a feature.</p>'
        f'<p><b>{active}</b> active claim(s) · <b>{subs}</b> submitted · claims last 30 days (extendable to 40), '
        'submissions show for 6 months.</p>'
        '<input id="q" placeholder="Search reviews / users…" oninput="var v=this.value.toLowerCase();'
        'Array.from(document.querySelectorAll(\'tbody tr\')).forEach(function(t){t.style.display=t.innerText.toLowerCase().indexOf(v)<0?\'none\':\'\'});" '
        'style="width:100%;padding:8px;margin:8px 0;background:#161b22;color:#e6edf3;border:1px solid #30363d;border-radius:6px">'
        '<table style="width:100%;border-collapse:collapse"><thead><tr style="opacity:.7;text-align:left">'
        '<th style="padding:6px">Review</th><th>Claimed by</th><th>Status</th></tr></thead>'
        f'<tbody>{trs or "<tr><td colspan=3 style=opacity:.6>No open claims yet.</td></tr>"}</tbody></table>'
        '<p style="opacity:.6;font-size:12px;margin-top:12px">Generated from the public claims repo by a daily '
        'GitHub Action. No server, no database — it survives us.</p></div>')
    open(out_path, 'w', encoding='utf-8').write(html)
    return active, subs


if __name__ == '__main__':
    if hasattr(sys.stdout, 'buffer'):
        import io
        sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
    # demo with sample claims (fixed epoch)
    T0 = 1_000_000_000
    sample = [C.new_claim('MALARIA_ACT', 'amina', T0 - 3*C.DAY),
              C.new_claim('TB_XPERT_DTA', 'bosco', T0 - 20*C.DAY),
              C.new_claim('HIV_PREP', 'amina', T0 - 35*C.DAY)]   # this one lapsed
    C.mark_submitted(sample[1], T0 - 8*C.DAY)
    out = os.path.join(REPO, 'outputs', 'reviews_board.html')
    a, s = build(sample, T0, out)
    print(f"board built: {a} active, {s} submitted -> outputs/reviews_board.html")
    # confirm search + banner text present
    h = open(out, encoding='utf-8').read()
    print("  banner shows 'days left':", 'days left' in h, "| submitted badge:", 'submitted' in h,
          "| inform-not-block text:", 'never blocks' in h, "| search box:", 'Search reviews' in h)
