"""Render HTA_CEILING.md FROM evidence/2026-09-02-hta-ceiling/hta_ceiling.json.

The markdown is generated, never hand-edited. A hand-maintained copy of a
measured list is a second number for one quantity, and this project has spent
a night establishing what that costs.
"""
import io
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "evidence", "2026-09-02-hta-ceiling",
                   "hta_ceiling.json")
USABLE = os.path.join(ROOT, "evidence", "2026-09-02-hta-ceiling",
                      "ceiling_usable.json")
OUT = os.path.join(ROOT, "HTA_CEILING.md")


def main():
    d = json.load(io.open(SRC, encoding="utf-8"))
    L = []
    a = L.append
    a("# Which topics can carry an HTA table, and what the ceiling is")
    a("")
    a("GENERATED by `scripts/emit_hta_ceiling_md.py` from")
    a("`evidence/2026-09-02-hta-ceiling/hta_ceiling.json`, which is written by")
    a("`scripts/hta_ceiling.py`. Do not hand-edit: re-run the pair.")
    a("")
    a("## The unit, before any number")
    a("")
    a("**OBJECT** = one file matching `ssot/*/*.json` carrying an `app_id`.")
    a("This is the unit of every denominator on this page. It is **not** a")
    a("page, **not** a rendered card, **not** an outcome, and **not** a topic")
    a("directory.")
    a("")
    a("**OUTCOME** = one key under `results.by_outcome` of an OBJECT. An")
    a("object holds 0..n outcomes. **Outcomes are not topics** and the two")
    a("counts must never be quoted against each other's denominator.")
    a("")
    a("**LIVE** = an outcome whose `pooled` block holds a point estimate and")
    a("is not withdrawn. Only a LIVE outcome can carry a Summary-of-Findings")
    a("or HTA row.")
    a("")
    a("## The counts")
    a("")
    a("| quantity | unit | n |")
    a("|---|---|---|")
    a("| objects in the store | OBJECT | %d |" % d["n_objects"])
    a("| **hold >= 1 live pooled estimate** | OBJECT | **%d** |"
      % d["n_objects_with_live_pooled_estimate"])
    a("| hold none | OBJECT | %d |" % d["n_objects_without"])
    a("| live pooled outcomes across those objects | OUTCOME | %d |"
      % d["n_live_pooled_outcomes"])
    a("")
    a("Identity: %d + %d = %d."
      % (d["n_objects_with_live_pooled_estimate"],
         d["n_objects_without"], d["n_objects"]))
    a("")
    a("## The %d objects that can carry an HTA table"
      % d["n_objects_with_live_pooled_estimate"])
    a("")
    a("`needs period` marks a measure whose conversion to an absolute risk")
    a("requires proportional hazards and a stated time horizon (HR,")
    a("RATE_RATIO, IRR). `period` is quoted verbatim from the object with the")
    a("field it was read from; an empty period on a row that needs one means")
    a("the row declines as `NOT_ESTIMABLE_NO_TIME_HORIZON`.")
    a("")
    a("| topic key | outcome | measure | needs period | period | read from |")
    a("|---|---|---|---|---|---|")
    for o in d["objects_with_live_pooled_estimate"]:
        for r in o["outcomes"]:
            a("| `%s` | `%s` | %s | %s | %s | %s |"
              % (o["topic"], r["outcome"], r["measure"],
                 "yes" if r["needs_time_horizon"] else "-",
                 (r["time_horizon"] or "-").replace("|", "\\|"),
                 "`%s`" % r["time_horizon_field"]
                 if r["time_horizon_field"] else "-"))
    a("")
    a("## Is the ceiling real, or the ceiling of what we stored?")
    a("")
    a("Of the %d objects holding no live pooled estimate:"
      % d["n_objects_without"])
    a("")
    a("| state | unit | n | meaning |")
    a("|---|---|---|---|")
    s = d["states_of_objects_without"]
    a("| `COMPUTABLE_NOT_COMPUTED` | OBJECT | %d | two or more trials hold a "
      "2x2 for the same outcome. A fixable gap; it raises the ceiling. |"
      % s.get("COMPUTABLE_NOT_COMPUTED", 0))
    a("| `SINGLE_TRIAL_CELLS_ONLY` | OBJECT | %d | one trial holds cells. An "
      "estimate is possible, a pooled one is not. |"
      % s.get("SINGLE_TRIAL_CELLS_ONLY", 0))
    a("| `CELLS_TRIAL_LEVEL_ONLY` | OBJECT | %d | arms or registration counts "
      "exist but describe the trial's PRIMARY endpoint, not a named outcome. "
      "A lead to chase by hand, never a derivation. |"
      % s.get("CELLS_TRIAL_LEVEL_ONLY", 0))
    a("| `NO_CELLS_AND_SIDECAR_WAS_READ` | OBJECT | %d | looked at, nothing "
      "there. A real data gap. |"
      % s.get("NO_CELLS_AND_SIDECAR_WAS_READ", 0))
    a("| `NOT_MEASURED_NO_SIDECAR_MAPPED` | OBJECT | %d | **never looked at.** "
      "No `outputs/r_validation` sidecar resolved for the topic. NOT a data "
      "gap. |" % s.get("NOT_MEASURED_NO_SIDECAR_MAPPED", 0))
    a("")
    a("Identity: %d = %d."
      % (sum(s.values()), d["n_objects_without"]))
    a("")
    a("| ceiling | unit | n |")
    a("|---|---|---|")
    a("| today | OBJECT | %d of %d |"
      % (d["ceiling_today_objects"], d["n_objects"]))
    a("| if the computable are computed | OBJECT | %d of %d |"
      % (d["ceiling_if_computable_computed_objects"], d["n_objects"]))
    a("")
    unm = d.get("ceiling_is_a_lower_bound_because_unmapped", 0)
    checked = d["n_objects_without"] - unm
    a("**The second figure is a LOWER BOUND.** %d of the %d objects without an"
      % (unm, d["n_objects_without"]))
    a("estimate were never looked at for out-of-object cells, because the")
    a("topic-to-sidecar mapper resolved for only %d of %d. Among the %d that"
      % (d["objects_without_mapped_to_a_sidecar"], d["n_objects_without"],
         checked))
    a("**were** looked at, %d were computable."
      % s.get("COMPUTABLE_NOT_COMPUTED", 0))
    a("")
    a("So the next lever is the **mapper**, not the evidence. Improving")
    a("topic-to-sidecar resolution is what moves this number, and until it")
    a("improves, `NOT_MEASURED_NO_SIDECAR_MAPPED` must never be quoted or")
    a("aggregated as though it meant `NO_CELLS`.")
    a("")
    a("## Computable is not usable")
    a("")
    u = json.load(io.open(USABLE, encoding="utf-8"))
    us = u["states"]
    a("Every one of the %d objects classed `COMPUTABLE_NOT_COMPUTED` **already"
      % u["denominator_computable_not_computed"])
    a("holds a pooled estimate and interval** in its `outputs/r_validation`")
    a("sidecar. They are not merely computable; they are computed and unused.")
    a("")
    a("But k is 2 or 3 for most of them, and a REML+HKSJ interval at k=2 with")
    a("high heterogeneity is enormous by construction. Quoting the raw count")
    a("as a ceiling would promise tables whose 95% interval spans seventy")
    a("orders of magnitude. Criterion, chosen on principle and not fitted:")
    a("an interval is DEGENERATE when `ci_high / ci_low > %g`, or a bound is"
      % u["threshold_ci_high_over_ci_low"])
    a("non-positive or non-finite.")
    a("")
    a("| state | unit | n |")
    a("|---|---|---|")
    a("| `USABLE` | OBJECT | %d |" % us.get("USABLE", 0))
    a("| `DIRECTION_CONFLICTED` | OBJECT | %d |"
      % us.get("DIRECTION_CONFLICTED", 0))
    a("| `DEGENERATE_INTERVAL` | OBJECT | %d |"
      % us.get("DEGENERATE_INTERVAL", 0))
    a("")
    a("`DIRECTION_CONFLICTED` exists because interval width alone is not")
    a("enough, and that was demonstrated rather than theorised.")
    a("`pcsk9-inhibitors-cv-review` passed the width test at OR 6.35 (1.26 to")
    a("32.1) -- the wrong direction for PCSK9 inhibitors on cardiovascular")
    a("events. Its per-trial odds ratios run from 0.41 to 362: FOURIER and")
    a("ODYSSEY OUTCOMES sit near 0.84 (CV events, protective) while ORION-10,")
    a("ORION-11 and BERSON sit at 35 to 401, which is an LDL-C")
    a("target-attainment outcome where benefit means MORE events. The pool")
    a("combines quantities that are not the same quantity, and I-squared of")
    a("99.8% is the tell. A narrow interval around an incommensurable pool is")
    a("worse than a wide one, not better.")
    a("")
    a("`USABLE` means the interval carries decision content and the")
    a("contributing trials do not contradict each other in direction. It does")
    a("**not** mean the estimate is correct or that the topic should be")
    a("published -- several carry I-squared above 90%, and that is a separate")
    a("judgement that this measurement does not make.")
    a("")
    a("| ceiling | unit | n |")
    a("|---|---|---|")
    a("| today | OBJECT | %d of %d |"
      % (d["ceiling_today_objects"], d["n_objects"]))
    a("| plus computable, any interval | OBJECT | %d of %d |"
      % (d["ceiling_if_computable_computed_objects"], d["n_objects"]))
    a("| **plus computable with a usable interval** | OBJECT | **%d of %d** |"
      % (d["ceiling_today_objects"] + us.get("USABLE", 0), d["n_objects"]))
    a("")
    a("Identity across the %d computable objects: %d usable + %d "
      "direction-conflicted + %d degenerate = %d."
      % (u["denominator_computable_not_computed"], us.get("USABLE", 0),
         us.get("DIRECTION_CONFLICTED", 0),
         us.get("DEGENERATE_INTERVAL", 0),
         sum(us.values())))
    a("")
    a("**The target of twenty is comfortable, not tight.**")
    a("")
    a("## Topics that are computable but not computed")
    a("")
    a("| topic key | trials with a 2x2 on one outcome | in-object | sidecar |")
    a("|---|---|---|---|")
    for x in d["objects_without_live_pooled_estimate"]:
        if x["state"] == "COMPUTABLE_NOT_COMPUTED":
            a("| `%s` | %d | %d | %d |"
              % (x["topic"], x["max_trials_with_cells_for_one_outcome"],
                 x["from_in_object"], x["from_sidecar"]))
    a("")
    io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(L))
    print("wrote %s (%d lines)" % (os.path.relpath(OUT, ROOT), len(L)))


if __name__ == "__main__":
    main()
