"""Round 4: the patient-facing surface.

The Waiting Room and Patient Mode panels are generated by their own code paths and
carried the same finerenone/cardio-renal template contamination the scientific
narrative did - "major heart and kidney events", "compared with placebo" - plus a
Significant Benefit / Significant Harm chip driven by the DerSimonian-Laird bounds
alone, which contradicts the verdict banner fixed in round 3.

Run after rounds 1-3:  python scripts/fix_doac_cancer_vte_round4.py
"""
import io
import os
import sys

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

TARGET = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..',
                                       'DOAC_CANCER_VTE_REVIEW.html'))
EDITS = []


def edit(tag, old, new, count=1):
    EDITS.append((tag, old, new, count))


def build_edits():
    edit('waiting room: cardio-renal wording, placebo comparator, and a DL-only '
         'significance chip that disagreed with the verdict banner',
         'sigText=parseFloat(r.uci)<1?"Significant Benefit":parseFloat(r.lci)>1?'
         '"Significant Harm":"Not Significant"',
         'sigText=(parseFloat(r.uci)<1&&!(parseFloat(r.hksjUCI)>=1))?"Significant Benefit":'
         '(parseFloat(r.lci)>1&&!(parseFloat(r.hksjLCI)<=1))?"Significant Harm":"Not Significant"')

    edit('waiting room: plain-language message named the wrong disease and the wrong comparator',
         'plainMsg=parseFloat(r.uci)<1?"DOACs reduced the risk of major heart and kidney events '
         'by about "+Math.round(absRRR)+"% compared with placebo across "+r.k+" clinical trials '
         'with "+r.n+" patients.":parseFloat(r.lci)>1?"DOACs was associated with a "+'
         'Math.round(absRRR)+"% higher risk of events compared with placebo across "+r.k+'
         '" trials ("+r.n+" patients). Discuss with your doctor.":"The evidence from "+r.k+'
         '" trials ("+r.n+" patients) did not show a clear benefit or harm for this outcome."',

         'plainMsg="Not Significant"!==sigText&&parseFloat(r.uci)<1?"Blood-thinning tablets '
         '(DOACs) lowered the chance of another blood clot by about "+Math.round(absRRR)+'
         '"% compared with daily heparin injections, across "+r.k+" trials in "+r.n+'
         '" people with cancer. Discuss with your doctor.":"Not Significant"!==sigText&&'
         'parseFloat(r.lci)>1?"Blood-thinning tablets (DOACs) were linked to about a "+'
         'Math.round(absRRR)+"% higher chance of this event than daily heparin injections, '
         'across "+r.k+" trials in "+r.n+" people with cancer. Discuss with your doctor."'
         ':"Across "+r.k+" trials in "+r.n+" people with cancer, blood-thinning tablets (DOACs) '
         'and daily heparin injections came out close enough that this study cannot say which is '
         'better for this outcome. Discuss with your doctor."')

    edit('patient mode: outcome vocabulary was cardio-renal',
         'outcomeText={default:"major cardiovascular events",MACE:"major cardiovascular events",'
         'HF_CV_First:"heart failure worsening or cardiovascular death",'
         'Renal40:"major kidney events",KidneyComp:"kidney events",'
         'ACM:"death from any cause",ACH:"hospitalization for heart failure",'
         'Hyperkalemia:"hyperkalemia events"}[String(RapidMeta.state.selectedOutcome??"default")]'
         '??"the selected outcome"',
         'outcomeText={default:"another blood clot",VTE:"another blood clot",'
         'MACE:"major cardiovascular events",'
         'MajBleed:"serious bleeding",Composite:"another blood clot or serious bleeding",'
         'HF_CV_First:"heart failure worsening or cardiovascular death",'
         'Renal40:"major kidney events",KidneyComp:"kidney events",'
         'ACM:"death from any cause",ACH:"hospitalization for heart failure",'
         'Hyperkalemia:"hyperkalemia events"}[String(RapidMeta.state.selectedOutcome??"default")]'
         '??"the selected outcome"')

    edit('narrative: do not say "statistically significant" when the HKSJ interval spans 1',
         'effectClause="benefit"===effect.direction?`demonstrated a statistically significant '
         '<span class="nyt-stat-inline">${effect.pct}%</span> reduction in ${ocProse}`:'
         '"harm"===effect.direction?`demonstrated a statistically significant '
         '<span class="nyt-stat-inline">${effect.pct}%</span> increase in ${ocProse}`:',

         'effectClause="benefit"===effect.direction&&effect.significant?`demonstrated a '
         'statistically significant <span class="nyt-stat-inline">${effect.pct}%</span> '
         'reduction in ${ocProse}`:"harm"===effect.direction&&effect.significant?`demonstrated '
         'a statistically significant <span class="nyt-stat-inline">${effect.pct}%</span> '
         'increase in ${ocProse}`:effect.hksjDisagrees?`were associated with an estimated '
         '<span class="nyt-stat-inline">${effect.pct}%</span> '
         '${parseFloat(r.or)<=1?"reduction":"increase"} in ${ocProse} that is NOT statistically '
         'significant once the small number of trials is accounted for (the HKSJ interval, which '
         'this protocol pins as the interval to quote, includes no effect)`:')


def main():
    raw = open(TARGET, 'rb').read()
    had_bom = raw.startswith(b'\xef\xbb\xbf')
    src = raw.decode('utf-8-sig')
    build_edits()
    for tag, old, new, count in EDITS:
        found = src.count(old)
        if found != count:
            sys.exit('ANCHOR MISMATCH [%s]: expected %d, found %d\n  anchor: %.200s'
                     % (tag, count, found, old))
        src = src.replace(old, new)
    out = src.encode('utf-8')
    if had_bom:
        out = b'\xef\xbb\xbf' + out
    with open(TARGET, 'wb') as fh:
        fh.write(out)
    print('applied %d anchored edits (round 4)' % len(EDITS))
    for tag, _, _, _ in EDITS:
        print('  -', tag)


if __name__ == '__main__':
    main()
