#!/usr/bin/env python
"""Generate R validation script + run + save JSON for any NMA config.

Takes the same JSON config as clone_nma_review.py and produces:
  nma/validation/<slug>_netmeta.R
  nma/validation/<slug>_netmeta_results.txt
  nma/validation/<slug>_netmeta_results.json
  nma/validation/<slug>_netmeta_results.rds

Usage: python nma_r_validate_template.py <config.json>
"""
import json, sys, io, re, subprocess
from pathlib import Path

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

import os
import shutil
RSCRIPT = os.environ.get("RSCRIPT") or shutil.which("Rscript") or \
    os.environ.get("RAPIDMETA_RSCRIPT", "C:/Program Files/R/R-4.5.2/bin/Rscript.exe")
ROOT = Path(os.environ.get("RAPIDMETA_ROOT") or Path(__file__).resolve().parents[1])
VALIDATION_DIR = ROOT / "nma" / "validation"

R_TEMPLATE = r'''## {title} — netmeta validation
## Auto-generated by nma_r_validate_template.py
suppressPackageStartupMessages({{ library(netmeta); library(meta) }})

logHR_SE <- function(hr, lci, uci) {{
  list(TE = log(hr), seTE = (log(uci) - log(lci)) / 3.92)
}}

# From config.comparisons + config.realData (one row per edge×trial)
trials <- data.frame(
  studlab = c({studlab}),
  treat1  = c({treat1}),
  treat2  = c({treat2}),
  TE      = c({TE}),
  seTE    = c({seTE}),
  stringsAsFactors = FALSE
)
cat("=== {title} ===\n")
print(trials)
cat("\n")

nma <- netmeta(TE=TE, seTE=seTE, treat1=treat1, treat2=treat2, studlab=studlab,
               data=trials, sm="{sm}", reference.group="{ref}",
               common=TRUE, random=TRUE,
               method.tau="REML",   # REML per protocol (NOT DL, which is the netmeta default)
               hakn=TRUE)            # HKSJ (Hartung-Knapp-Sidik-Jonkman) CI adjustment

cat("\n=== Consistency model ===\n")
print(summary(nma))
cat("\n=== League table (RE, HR/RR with 95% CI) ===\n")
print(netleague(nma, digits=3, common=FALSE, random=TRUE)$random)
cat("\n=== Design-by-treatment inconsistency ===\n")
print(decomp.design(nma))
cat("\n=== Node-splitting ===\n")
print(netsplit(nma, common=FALSE, random=TRUE))
cat("\n=== P-scores (lower = better for HR/RR on protective scale) ===\n")
rk <- netrank(nma, small.values="{small}", common=FALSE, random=TRUE)
print(rk)

# MC rank-probability matrix — correct multivariate-normal draw using
# netmeta's estimated contrast vcov (not independent rnorms; bug acknowledged
# in v1.0 of this script, fixed 2026-04-21).
set.seed(42)
suppressPackageStartupMessages(library(MASS))
n_draws <- 1e5
trts <- nma$trts
n_trt <- length(trts)
non_ref <- trts[trts != "{ref}"]
# Mean vector: contrast vs reference for non-reference treatments
mu <- nma$TE.random[non_ref, "{ref}"]
# Full covariance of contrasts from the fitted random-effects model
if (!is.null(nma$Cov.random)) {{
  # Cov.random is keyed on treatment × treatment; extract the subset vs reference.
  # netmeta stores this as a matrix indexed by trt names in the trts order.
  cov_full <- nma$Cov.random
  # Construct contrast-vs-ref covariance for non_ref × non_ref
  # Sigma[i,j] = Cov(mu_i - mu_ref, mu_j - mu_ref)
  idx_ref <- which(trts == "{ref}")
  idx <- which(trts %in% non_ref)
  Sigma <- matrix(0, nrow=length(non_ref), ncol=length(non_ref),
                  dimnames=list(non_ref, non_ref))
  for (a in seq_along(non_ref)) for (b in seq_along(non_ref)) {{
    ia <- which(trts == non_ref[a]); ib <- which(trts == non_ref[b])
    Sigma[a, b] <- cov_full[ia, ib] - cov_full[ia, idx_ref] -
                   cov_full[idx_ref, ib] + cov_full[idx_ref, idx_ref]
  }}
}} else {{
  # Fallback: independent — clearly marked as a limitation in this case
  Sigma <- diag(nma$seTE.random[non_ref, "{ref}"]^2)
  warning("Cov.random unavailable; falling back to independent-contrast MC draws. Results approximate.")
}}
draws_nonref <- mvrnorm(n_draws, mu, Sigma)
draws <- matrix(0, nrow=n_draws, ncol=n_trt)
colnames(draws) <- trts
for (i in seq_along(non_ref)) draws[, non_ref[i]] <- draws_nonref[, i]
# Direction: small.values="desirable" -> rank 1 = smallest (e.g., HR<1 is best)
# small.values="undesirable" -> rank 1 = largest (e.g., OR>1 is best for PASI 90)
if ("{small}" == "undesirable") draws <- -draws
ranks <- t(apply(draws, 1, rank, ties.method="random"))
colnames(ranks) <- trts
rank_prob <- matrix(0, nrow=n_trt, ncol=n_trt,
                    dimnames=list(trts, paste0("rank_", seq_len(n_trt))))
for (i in seq_len(n_trt)) for (r in seq_len(n_trt)) rank_prob[i, r] <- mean(ranks[, i] == r)
sucra <- sapply(seq_len(n_trt), function(i) mean(cumsum(rank_prob[i, -n_trt])))
names(sucra) <- trts
cat("\n=== Rank-probability matrix (N=100k draws) ===\n")
print(round(rank_prob, 3))
cat("\n=== SUCRA ===\n")
print(round(sort(sucra, decreasing=TRUE), 3))

# JSON output
# Back-transform: ratio measures use exp(), MD/SMD use identity
is_log <- "{sm}" %in% c("HR", "OR", "RR")
bt <- if (is_log) exp else function(x) x
results <- list(
  title = "{title}",
  treatments = trts,
  te_random_vs_ref   = setNames(nma$TE.random[, "{ref}"], trts),
  se_random_vs_ref   = setNames(nma$seTE.random[, "{ref}"], trts),
  hr_random_vs_chemoimm = setNames(bt(nma$TE.random[, "{ref}"]), trts),
  hr_ci_lower   = setNames(bt(nma$lower.random[, "{ref}"]), trts),
  hr_ci_upper   = setNames(bt(nma$upper.random[, "{ref}"]), trts),
  tau2 = nma$tau^2,
  I2 = nma$I2,
  Q_total = nma$Q,
  Q_heterogeneity = nma$Q.heterogeneity,
  Q_inconsistency = nma$Q.inconsistency,
  p_inconsistency = nma$pval.Q.inconsistency,
  sucra = sucra,
  pscore_random = rk$ranking.random,
  rank_prob = rank_prob
)
saveRDS(results, "{slug}_netmeta_results.rds")
tryCatch({{
  suppressPackageStartupMessages(library(jsonlite))
  writeLines(toJSON(lapply(results, function(x) if (is.matrix(x)) {{ m <- as.matrix(x); dimnames(m) <- NULL; m }} else x), digits=6, auto_unbox=TRUE),
             "{slug}_netmeta_results.json")
  cat("\n[wrote {slug}_netmeta_results.rds + .json]\n")
}}, error = function(e) cat("\n[JSON skipped:", conditionMessage(e), "]\n"))
cat("\n=== Key results for peer-review bundle ===\n")
cat("TAU2:", round(nma$tau^2, 5), "\n")
cat("I2:", round(nma$I2 * 100, 2), "%\n")
cat("Q inc:", round(nma$Q.inconsistency, 3), "df", nma$df.Q.inconsistency, "p", round(nma$pval.Q.inconsistency, 4), "\n")
for (tr in trts) {{
  if (tr == "{ref}") next
  cat(sprintf("  %-24s %s %.3f (%.3f, %.3f)\n",
              tr, "{sm}",
              bt(nma$TE.random[tr, "{ref}"]),
              bt(nma$lower.random[tr, "{ref}"]),
              bt(nma$upper.random[tr, "{ref}"])))
}}
'''


def extract_effects_from_config(cfg):
    """For each comparison × trial, pull effect + SE from realData block.

    Handles both log-scale measures (HR / OR / RR → log-transform) and
    linear-scale measures (MD / SMD → pass through on native scale).
    Scale determined by `cfg['effect_scale']`.
    """
    data = cfg["realData_block"]
    scale = cfg.get("effect_scale", "HR").upper()
    is_log_scale = scale in ("HR", "OR", "RR")
    # Extract per-NCT { name, publishedHR, hrLCI, hrUCI } (signed numbers OK for MD)
    pattern = re.compile(
        r"'(NCT\d+[A-Z]?)':\s*\{\s*name:\s*'([^']+)'[^}]*?publishedHR:\s*(-?[\d.]+)[^}]*?hrLCI:\s*(-?[\d.]+)[^}]*?hrUCI:\s*(-?[\d.]+)",
        re.DOTALL
    )
    trials_data = {}
    for m in pattern.finditer(data):
        nct, name, hr, lci, uci = m.group(1), m.group(2), float(m.group(3)), float(m.group(4)), float(m.group(5))
        import math
        if is_log_scale:
            te = math.log(hr)
            se = (math.log(uci) - math.log(lci)) / 3.92
        else:
            # MD / SMD — native scale
            te = hr  # `publishedHR` stores the MD value when effect_scale is MD
            se = (uci - lci) / 3.92
        trials_data[nct] = {"name": name, "te": te, "se": se, "hr": hr, "lci": lci, "uci": uci}

    rows = []
    for cmp in cfg["comparisons"]:
        for trial_id in cmp.get("trials", []):
            if trial_id not in trials_data:
                print(f"WARN: trial {trial_id} not in realData (may have CONTINUOUS scale); skipping")
                continue
            td = trials_data[trial_id]
            rows.append({
                "studlab": td["name"],
                "treat1": cmp["t1"],
                "treat2": cmp["t2"],
                "TE": td["te"],
                "seTE": td["se"]
            })
    return rows


def generate_r_script(cfg):
    rows = extract_effects_from_config(cfg)
    if not rows:
        raise RuntimeError("no parseable trial effects in realData_block")
    # Pick reference group (last treatment by convention, or "Placebo" / "Chemoimm" / "Sham")
    ref = None
    for candidate in ["Placebo", "placebo", "Sham", "Chemoimmunotherapy", "Chemoimm"]:
        if candidate in cfg["treatments"]:
            ref = candidate
            break
    if ref is None:
        ref = cfg["treatments"][-1]

    sm = cfg.get("effect_scale", "HR")  # HR or RR or OR
    small = cfg.get("small_better", "desirable")  # "desirable" if lower HR = better

    script = R_TEMPLATE.format(
        title=cfg["title"],
        slug=cfg["slug"],
        sm=sm,
        ref=ref,
        small=small,
        studlab=",".join(f'"{r["studlab"]}"' for r in rows),
        treat1=",".join(f'"{r["treat1"]}"' for r in rows),
        treat2=",".join(f'"{r["treat2"]}"' for r in rows),
        TE=",".join(f"{r['TE']:.10f}" for r in rows),
        seTE=",".join(f"{r['seTE']:.10f}" for r in rows),
    )
    return script


def main(cfg_path):
    cfg = json.load(open(cfg_path, "r", encoding="utf-8"))
    slug = cfg["slug"]
    VALIDATION_DIR.mkdir(parents=True, exist_ok=True)
    r_path = VALIDATION_DIR / f"{slug}_netmeta.R"
    script = generate_r_script(cfg)
    r_path.write_text(script, encoding="utf-8")
    print(f"wrote {r_path}")
    # Run it
    txt_path = VALIDATION_DIR / f"{slug}_netmeta_results.txt"
    print(f"running Rscript {r_path.name}...")
    try:
        result = subprocess.run(
            [RSCRIPT, r_path.name],
            cwd=VALIDATION_DIR,
            capture_output=True,
            text=True,
            encoding='utf-8',
            errors='replace',
            timeout=180
        )
        txt_path.write_text(result.stdout + result.stderr, encoding="utf-8")
        # Print key tail of output
        tail = result.stdout.strip().split('\n')[-20:] if result.stdout else result.stderr.split('\n')[-10:]
        print("\n".join(tail))
        if result.returncode != 0:
            print(f"WARN: Rscript exited {result.returncode}")
    except Exception as e:
        print(f"Rscript failed: {e}")
    return r_path


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("usage: python nma_r_validate_template.py <config.json>", file=sys.stderr)
        sys.exit(1)
    main(sys.argv[1])
