"""Does every object carry the fields its SIBLINGS of the same kind carry?

THE DEFECT THIS WOULD HAVE CAUGHT AT THE TIME. Eleven verdict-only closures built in one
session carried `inputs.trials[].registered_primaries`. Six more, built in the same session
for the same purpose, did not. The six were internally valid, passed every gate they met,
and the loss was invisible until something downstream asked for the field THREE ROUNDS
LATER.

WHY NO REVIEW WOULD HAVE FOUND IT, and this is the part worth keeping. The eleven were
generated by ONE SCRIPT from one cached registry read. The six were composed BY HAND, each
carrying what its own argument needed. `registered_primaries` was not load-bearing for
those six arguments, so it went. **A machine composing from one path cannot forget a field;
a person composing individually omits whatever is not load-bearing for the argument in
front of them.** That is RELEVANCE-DRIVEN OMISSION -- it feels like judgement while it
happens, and every one of those objects was complete for the purpose it was written for.

It is the same law we established for cards, jump lists, banners and manuscripts --
hand-authored surfaces drift -- APPLIED TO DATA RATHER THAN PRESENTATION, and the first
instance where the hand-authoring was ours, deliberate, and reasonable at the time.

THE CHECK: for each KIND of object, find the fields carried by MOST members, then report
the members missing them. A field on 11 of 17 siblings and absent on 6 is a signal
REGARDLESS of whether any consumer currently reads it -- because the consumer that will
read it may not exist yet.

THRESHOLD IS DELIBERATE AND STATED: a field must be present on >= 60% of a kind before its
absence elsewhere is reported. Lower and every optional field becomes noise; higher and a
narrowly-lost field like this one hides. It is a judgement, not a discovery, and it is
recorded so a reader can disagree with it.

NOT A VERDICT. A reported absence may be entirely correct -- some topics genuinely have no
heterogeneity because k=1. THIS TELLS YOU WHERE TO LOOK, NEVER WHAT YOU WILL FIND.
"""
from __future__ import annotations
import io
import json
import os
import sys

if __name__ == "__main__":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
THRESHOLD = 0.60


def kind_of(o):
    """Objects are compared only against their own kind."""
    bo = (o.get("results") or {}).get("by_outcome") or {}
    blk = bo.get("primary") or (list(bo.values())[0] if bo else {})
    if not isinstance(blk, dict):
        return "other"
    if (blk.get("pooled") or {}).get("point") is not None:
        return "pooled"
    if blk.get("poolable") is False:
        return "verdict-only"
    return "other"


def fields(o):
    """Top-level keys, plus the per-trial keys that carry provenance."""
    out = set(o.keys())
    trials = ((o.get("inputs") or {}).get("trials") or [])
    for t in trials:
        if isinstance(t, dict):
            for k in t:
                out.add("inputs.trials[].%s" % k)
    return out


def main() -> int:
    ss = os.path.join(REPO, "ssot")
    objs = {}
    for d in sorted(os.listdir(ss)):
        f = os.path.join(ss, d, d + ".json")
        if not os.path.exists(f):
            continue
        try:
            objs[d] = json.load(io.open(f, encoding="utf-8"))
        except Exception:
            continue

    bykind = {}
    for d, o in objs.items():
        bykind.setdefault(kind_of(o), {})[d] = fields(o)

    total_flags = 0
    for kind in sorted(bykind):
        members = bykind[kind]
        n = len(members)
        if n < 4:
            print("%-14s %2d members -- too few to establish a norm, skipped" % (kind, n))
            continue
        counts = {}
        for fs in members.values():
            for f in fs:
                counts[f] = counts.get(f, 0) + 1
        expected = {f for f, c in counts.items() if c / n >= THRESHOLD}
        print()
        print("=== %s -- %d members, %d fields carried by >=%d%%"
              % (kind, n, len(expected), int(THRESHOLD * 100)))
        rows = []
        for d, fs in sorted(members.items()):
            miss = sorted(expected - fs)
            if miss:
                rows.append((d, miss))
        for d, miss in rows[:14]:
            total_flags += 1
            print("    %-42s missing %d: %s" % (d[:41], len(miss), ", ".join(miss)[:58]))
        if len(rows) > 14:
            print("    ... and %d more" % (len(rows) - 14))
        if not rows:
            print("    every member carries every field its siblings carry.")

    print()
    print("objects flagged: %d" % total_flags)
    print("A REPORTED ABSENCE MAY BE ENTIRELY CORRECT -- some topics genuinely lack a")
    print("field. THIS TELLS YOU WHERE TO LOOK, NEVER WHAT YOU WILL FIND. The %d%%"
          % int(THRESHOLD * 100))
    print("threshold is a judgement, recorded so a reader can disagree with it.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
