# -*- coding: utf-8 -*-
"""THE MEASUREMENT: what the hand-written clinical reading claims, so a generated one can be
scored claim by claim.

WHY A LEDGER AND NOT A JUDGEMENT. "Equal to hand-written" is not scoreable as an impression. It
becomes scoreable when the hand-written section is decomposed into propositions, each with the
SOURCE that grounds it and the HEDGE it was written with, and a candidate is then measured
against that list: recall n of n, and separately whether each recalled claim kept its hedge.

⛔ THE HEDGE IS PART OF THE CLAIM. "The ring works in women over 21" and "a post hoc subgroup
showed 56% protection in women over 21" are different claims, and only the second is true of the
evidence. This project has already published a CONDITIONAL WHO recommendation as unconditional;
the same error one layer down turns a hypothesis-generating subgroup into a treatment decision.

⛔ AND BUILDING THIS FOUND ONE IMMEDIATELY. The hand-written section says "56% protection in the
age-stratified analysis". ASPIRE's own words are "IN A POST HOC ANALYSIS, higher rates of HIV-1
protection were observed among women over the age of 21 years (56%; 95% CI, 31 to 71)". The page
drops "post hoc". Its own Age section elsewhere calls the finding hypothesis-generating, so the
review knows -- the clinical reading, the part a busy clinician actually reads, does not say it.

MEASURED ERROR RATES, BOTH DIRECTIONS. A checker with no measured error rate is an assumption
wearing a number, so this one was measured against adversarial sets rather than asserted:

  SENSITIVITY  14 of 14 single-hedge ablations detected. Each ablation is the passage with
               exactly ONE hedge removed. The first version scored 10 of 14; both misses were
               C3's COMPOUND hedge ("about 45 ... roughly 18 months"), where a flat any() let
               either survivor satisfy the test.
  SPECIFICITY  8 of 8 hedge-preserving paraphrases passed clean, zero false flags, at
               similarity 0.736 to 0.904 against the original -- i.e. genuine rewordings of
               10-26% of the text, not near-copies.

  RECALL       BRITTLE, AND MEASURED SO. Against 8 RADICAL rewrites (similarity 0.28-0.54,
               same claims, same hedges, different words) recall fell to 13-14 of 16. Replacing
               word-overlap with concept groups moved clean runs only from 1 of 8 to 2 of 8 and
               cost one specificity case (8/8 -> 7/8). What still fails: C8/C9 "no excess of
               severe/serious adverse events" (5 of 8 each), C11 "protects against nothing else"
               (5), C6 "would overstate what is known" (4).

⛔ AND I STOPPED TUNING RATHER THAN CHASE THOSE. Each extra synonym would have been copied from
the very rewrites used to measure the instrument, which fits the validation set and destroys the
only number I have about it. THE MECHANISM IS THE LIMIT, not the vocabulary: string matching
cannot recognise "rates were similar between groups" as "no excess of serious adverse events".
Recall against arbitrary rewording needs an entailment check, which is a model call and a design
decision, not a patch.

⇒ WHAT THIS INSTRUMENT IS FIT FOR. Scoring a GENERATED clinical reading written from the same
claim set -- i.e. a moderate paraphrase, where specificity is 7-8 of 8 and the hedge check is
14/14. It is NOT fit for judging an independently written section that happens to say the same
things. Reporting a low recall on such a text would be a fact about this checker.

⚠️ ALL THREE ADVERSARIAL SETS ARE NOW BURNED for the recall mechanism. The sensitivity and
specificity figures above predate the recall change and are unaffected by it; any future recall
figure needs a set generated after these groups were written.

PROVENANCE OF THE ENUMERATION. Propositions were enumerated mechanically by codex (GPT-5, no
network, evidence inline) and the modal/polarity assignments were checked by hand. Both
adversarial sets -- ablations and paraphrases -- were generated by codex too, which is the right
use of it: mechanical variation of text already in hand. Sources were retrieved and verified
here; codex was given no retrieval role because it has none.
"""
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
os.chdir(os.path.dirname(os.path.dirname(HERE)))

ASPIRE = "ASPIRE primary, PMID 26900902, PMC4993693, doi 10.1056/NEJMoa1506110, retrieved 2026-08-30"
WHO = "WHO guideline, iris handle 10665/340190, 17 March 2021, retrieved 2026-08-29"
PAGE = "computed on this page from the adjudicated counts"

# id, verbatim span, the proposition, the hedge AS WRITTEN, polarity, source, grounded?
CLAIMS = [
    ("C1", "In women over 21 the ring works",
     "In women over 21 the ring works", "unhedged assertion", "assert", ASPIRE, "HEDGE_WEAKER",
     "ASPIRE calls this a POST HOC analysis; the page states it flat. A post-hoc subgroup "
     "presented as a finding is the difference between a hypothesis and a recommendation."),
    ("C2", "56% protection in the age-stratified analysis",
     "56% protection in the age-stratified analysis", "unhedged assertion", "assert", ASPIRE,
     "GROUNDED_PARTIAL",
     "The figure is exact -- 56% (95% CI, 31 to 71) -- but the source says post hoc, and the "
     "page gives no interval where the source gives one."),
    ("C3", "about 45 women using it for roughly 18 months prevents one infection",
     "NNT about 45 over roughly 18 months", "about; roughly", "assert", PAGE, "GROUNDED",
     "Derived on the page from the adjudicated pool and stated with its range elsewhere (30 to 116)."),
    ("C4", "In women 21 and under it has not been shown to work",
     "In women 21 and under efficacy has not been shown", "has not been shown", "cannot-determine",
     ASPIRE, "GROUNDED",
     "ASPIRE: -27% (95% CI, -133 to 31; P = 0.45). Absence of evidence, correctly not stated "
     "as evidence of absence."),
    ("C5", "these trials cannot say whether that is the product or the adherence",
     "The trials cannot separate product failure from non-adherence", "cannot say",
     "cannot-determine", ASPIRE, "GROUNDED",
     "ASPIRE ties the age difference to reduced adherence but does not resolve causation."),
    ("C6", "Offering it as though the pooled figure applied would overstate what is known",
     "Applying the pooled figure to under-21s would overstate what is known", "would", "predict",
     PAGE, "GROUNDED", "Follows from C2 and C4 holding together."),
    ("C7", "It is safe on everything measured",
     "The ring is safe on every outcome measured", "unhedged assertion", "assert", ASPIRE,
     "GROUNDED_SCOPED",
     "True of what was measured; the wording already scopes it with 'everything measured'."),
    ("C8", "no excess of severe or serious adverse events",
     "No excess of severe adverse events", "unhedged assertion", "deny", ASPIRE, "GROUNDED", ""),
    ("C9", "no excess of severe or serious adverse events",
     "No excess of serious adverse events", "unhedged assertion", "deny", ASPIRE, "GROUNDED", ""),
    ("C10", "no resistance signal among women who seroconverted",
     "No resistance signal among women who seroconverted", "unhedged assertion", "deny", ASPIRE,
     "GROUNDED", ""),
    ("C11", "It protects against nothing else",
     "The ring protects against nothing other than HIV-1", "unhedged assertion", "deny", WHO,
     "GROUNDED", "WHO records STI incidence unchanged; the ring is a single-agent ARV."),
    ("C12", "Condoms, STI screening and partner services remain necessary",
     "Condoms remain necessary", "remain necessary", "obligation", WHO, "GROUNDED",
     "WHO recommends the ring as part of COMBINATION prevention, not alone."),
    ("C13", "Condoms, STI screening and partner services remain necessary",
     "STI screening remains necessary", "remain necessary", "obligation", WHO, "GROUNDED", ""),
    ("C14", "Condoms, STI screening and partner services remain necessary",
     "Partner services remain necessary", "remain necessary", "obligation", WHO, "GROUNDED", ""),
    ("C15", "Effectiveness in use will be lower than this efficacy",
     "Real-world effectiveness will be lower than trial efficacy", "will", "predict", ASPIRE,
     "GROUNDED_INFERENCE",
     "An inference from trial-context adherence, not a measured quantity. Defensible and "
     "labelled here as inference rather than result."),
    ("C16", "which was already limited by adherence inside a trial with monthly contact",
     "Trial efficacy was already limited by adherence despite monthly contact", "unhedged "
     "assertion", "assert", ASPIRE, "GROUNDED", ""),
]

# Words that carry the hedge. A candidate that states the claim but drops these has not
# reproduced the claim -- it has reproduced a stronger one.
#
# ⛔ EVERY REQUIRED HEDGE MUST SURVIVE, NOT ANY ONE OF THEM. Each entry is a list of GROUPS; a
# group is a set of acceptable synonyms for one hedge, and the claim keeps its hedging only if
# EVERY group is satisfied.
#
# The first version was a flat any(): for C3, whose hedge is compound -- "ABOUT 45 women using
# it for ROUGHLY 18 months" -- deleting "about" left "roughly" to satisfy the test, and deleting
# "roughly" left "about". Measured against 14 single-hedge ablations generated by codex, the
# check scored 10 of 14; both misses were this. An instrument with no measured error rate is an
# assumption wearing a number, and ablation is how the number gets measured.
HEDGE_TOKENS = {
    "has not been shown": [["not been shown", "not demonstrated", "no evidence of benefit"]],
    "cannot say": [["cannot say", "cannot determine", "could not separate", "cannot distinguish",
                    "cannot tell"]],
    "would": [["would"]],
    "will": [["will", "expected to"]],
    "about; roughly": [["about", "approximately", "around", "some"],
                       ["roughly", "approximately", "around", "or so"]],
    "remain necessary": [["remain", "still necessary", "continue to"]],
}


# ⛔ RECALL BY CONCEPT, NOT BY WORD OVERLAP. Each entry is a list of GROUPS; the claim counts as
# recalled only if EVERY group has one of its members present. Authored from what each claim
# MEANS, not from the rewrites that exposed the problem.
#
# The first version required 60% overlap of the words longer than three characters in the
# verbatim span. Measured against 8 radical rewrites (similarity 0.28-0.54 to the original),
# recall fell to 13-14 of 16, and C6 and C11 were missed in SEVEN of eight. Both are short and
# idiomatic -- "it protects against nothing else" survives almost no rewording intact -- so the
# test was measuring phrasing, not content, exactly where a generated section will differ most.
#
# ⚠️ THE 8 REWRITES THAT EXPOSED THIS ARE NOW A BURNED VALIDATION SET. Re-measuring on them
# after this change tells us the mechanism works, NOT how well it generalises. An unbiased
# recall figure needs a fresh set generated after these groups were written.
RECALL_GROUPS = {
    "C1":  [["over 21", "older than 21", "above 21", "21 and over", "aged over 21"],
            ["works", "effective", "efficacy", "protect", "reduces", "reduction"]],
    "C2":  [["56"], ["protection", "efficacy", "reduction", "lower"]],
    "C3":  [["45"], ["18 month", "eighteen month", "year and a half"],
            ["one infection", "1 infection", "single infection", "prevent"]],
    "C4":  [["21 and under", "under 21", "younger than 21", "21 or younger", "up to 21"],
            ["not been shown", "not demonstrated", "no evidence", "unproven", "not shown"]],
    "C5":  [["cannot", "could not", "unable"],
            ["product", "ring itself", "drug"], ["adherence", "use", "wearing"]],
    "C6":  [["pooled", "overall figure", "combined", "average"],
            ["overstate", "oversell", "exaggerat", "more than is known", "beyond what"]],
    "C7":  [["safe", "safety"], ["measured", "assessed", "looked at", "studied"]],
    "C8":  [["severe"], ["no excess", "no increase", "not more", "no more", "without excess"]],
    "C9":  [["serious"], ["no excess", "no increase", "not more", "no more", "without excess"]],
    "C10": [["resistance"], ["no ", "not ", "none"]],
    "C11": [["nothing else", "no other", "only hiv", "not protect against other",
             "does not prevent other", "no protection against other", "hiv-1 only",
             "other infections", "other stis"]],
    "C12": [["condom"]],
    "C13": [["sti screening", "screening for sti", "infection screening", "sti testing"]],
    "C14": [["partner"]],
    "C15": [["effectiveness", "real world", "in practice", "everyday use"],
            ["lower", "less", "below"]],
    "C16": [["adherence"], ["monthly", "every month"]],
}


def score(candidate_text):
    """Recall n of n, and whether each recalled claim kept the hedge it was written with."""
    t = re.sub(r"\s+", " ", candidate_text or "").lower()
    rows = []
    for cid, verbatim, claim, modal, pol, src, grounded, note in CLAIMS:
        groups = RECALL_GROUPS.get(cid)
        if groups:
            present = all(any(m in t for m in g) for g in groups)
        else:
            key = [w for w in re.findall(r"[a-z0-9%]+", verbatim.lower()) if len(w) > 3]
            hit = sum(1 for w in key if w in t)
            present = len(key) > 0 and hit / len(key) >= 0.6
        kept = None
        if present and modal in HEDGE_TOKENS:
            kept = all(any(syn in t for syn in group) for group in HEDGE_TOKENS[modal])
        rows.append({"id": cid, "claim": claim, "modal": modal, "polarity": pol,
                     "grounded": grounded, "present": present, "hedge_kept": kept})
    return rows


def main():
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace",
                                  line_buffering=True)
    src = sys.argv[1] if len(sys.argv) > 1 else r"F:\claude-temp\pend\clinical_reading_handwritten.txt"
    text = io.open(src, encoding="utf-8", errors="replace").read()
    rows = score(text)
    n = len(rows)
    present = sum(1 for r in rows if r["present"])
    lost = [r for r in rows if r["present"] and r["hedge_kept"] is False]
    print("")
    print("CLINICAL READING -- claim ledger")
    print("")
    print("  propositions enumerated                 %3d" % n)
    for g in ("GROUNDED", "GROUNDED_PARTIAL", "GROUNDED_SCOPED", "GROUNDED_INFERENCE",
              "HEDGE_WEAKER"):
        c = sum(1 for c_ in CLAIMS if c_[6] == g)
        if c:
            print("    %-20s %3d" % (g, c))
    print("")
    print("  SCORED AGAINST: %s" % os.path.basename(src))
    print("    recall                                %3d of %d" % (present, n))
    print("    recalled but HEDGE DROPPED            %3d" % len(lost))
    for r in lost:
        print("      %-4s %s  (written: %s)" % (r["id"], r["claim"][:60], r["modal"]))
    missing = [r for r in rows if not r["present"]]
    if missing:
        print("")
        print("    NOT RECALLED:")
        for r in missing:
            print("      %-4s %-58s %s" % (r["id"], r["claim"][:58], r["modal"]))
    out = r"F:\claude-temp\pend\out\clinical_reading_score.json"
    os.makedirs(os.path.dirname(out), exist_ok=True)
    json.dump(rows, io.open(out, "w", encoding="utf-8"), indent=1)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
